Skatteetaten/vagrant-hashistack

CHANGELOG.md, ansible/group_vars/all/variables.yml, packer/cloud-push/variables.pkr.hcl
=> Version 0.0.1

.github/workflows/build.yml, .github/workflows/buld.yml, .github/workflows/release.yml
=> Add github action to build and optionally push on merge to master.

Makefile, README.md
=> Add prerequisites for mac-os

README.md
Closes #39 
Might be conflict with #42
=> Updated readme with transparent proxy

README.md, docs/CONTRIBUTING.md
=> Added contributing.md documentation.

README.md
=> Added default token section to readme

CHANGELOG.md, README.md, Vagrantfile, ansible/ansible.cfg, ansible/group_vars/all/variables.yml, ansible/playbook.yml, ansible/startup.yml, ansible/templates/consul.hcl.j2, ansible/templates/consul.service.j2, ansible/templates/nomad.hcl.j2, ansible/templates/nomad.service.j2, ansible/templates/vault.service.j2, test/Vagrantfile, test/ansible/ansible.cfg, vagrant/Vagrantfile
=> Fix startup issues and update documentation.

.github/workflows/build.yml, docs/CONTRIBUTING.md
=> release 0.0.8

.github/workflows/build.yml, CHANGELOG.md
Use release action from github directly
=> Release v0.1.1

README.md, ansible/playbook.yml
=> Small fixes 0.2

ansible/ansible.cfg, ansible/hosts, ansible/playbook.yml
=> Adding localhost to hosts file

.github/workflows/build.yml, template/dev/README.md
=> push dev template to vagrant-hashistack-template-dev

ansible/templates/consul.service.j2, ansible/templates/vault.service.j2
=> #103 Support config directory in hashistack

README.md
=> Doc update: removed outdated info, renamed/refactored a few sections

.github/workflows/build.yml, CHANGELOG.md, README.md, template/.github/workflows/build.yml, template/README.md, test/Makefile
=> Release 0.2.0

install/linux/Makefile
Made changes to install binaries on fresh linux box.
=> #138: Added fix for installing binaries on fresh linux box

README.md, install/linux/Makefile
Updated documentation and modified code to download curl binary if not found
=> 137 make install lack of binaries

README.md, ansible/bootstrap.yml, ansible/default_vars.yml, ansible/install.yml, ansible/templates/nomad-acl.hcl.j2, template/README.md, template/vagrant/conf/ansible/playbooks/prestart/1-acl.yml
This is a small PR to support ACLs with nomad. Scope creep was real with this one, so I dialed it back and made sure I had something simple that is working.
A PR that handles the acl bootstrap process, and stores everything in vault, will come later. 
~~EDIT: I forgot to update README, doing that now!~~
=> Nomad ACL toggle

ansible/bootstrap.yml, ansible/install.yml, ansible/nomad_acl_bootstrap.yml, ansible/templates/nomad-policies/read.policy.hcl, ansible/templates/nomad-policies/write.policy.hcl, template/README.md
Creating a draft PR that can run tests while I write documentation. Please do give feedback if you got any.
Closes #147
=> Nomad ACL bootstrap process

ansible/bootstrap.yml, ansible/install.yml, ansible/nomad_acl_bootstrap.yml, ansible/vault_nomad_integration.yml, template/README.md, template/terraform/main.tf
Leaving this as draft so it can run tests while I write documentation.
Closes #145
=> Roles in Vault for Nomad so that tokens can be issued by Vault

ansible/bootstrap.yml, template/test/vagrant/conf/ansible/playbooks/poststart/0-example.yml, template/test/vagrant/conf/ansible/playbooks/poststart/00-poststart-example.yml, template/test/vagrant/conf/ansible/playbooks/poststart/01-poststart-example.yml, template/test/vagrant/conf/ansible/playbooks/poststart/02-poststart-example.yml, template/test/vagrant/conf/ansible/playbooks/prestart/0-example.yml, template/test/vagrant/conf/ansible/playbooks/prestart/00-prestart-example.yml, template/test/vagrant/conf/ansible/playbooks/prestart/01-prestart-example.yml, template/test/vagrant/conf/ansible/playbooks/prestart/02-prestart-example.yml
=> run pre-poststart in lexical order. Add examples to show that happening.

README.md
=> Rephrase mission statement

CHANGELOG.md, packer/bootstrap.sh
Jq should be used to extract properties from consul/vault/nomad output. ( not awk/grep )
=> Install jq in vagrantbox

CHANGELOG.md, ansible/bootstrap.yml, ansible/install.yml, ansible/templates/consul-policies/admin.team.policy.hcl, ansible/templates/consul-policies/dev.team.policy.hcl, ansible/templates/consul-policies/key-policy.hcl, ansible/vault_consul_integration.yml, template/README.md
=> Consul secrets engine for vault

.github/workflows/on_pr_master.yml, template/test/Makefile
Run tests when consul policy is set to : allow or deny
=> Added test strategy matrix to run tests 

.github/action/create-env.py, .github/workflows/on_pr_master.yml
The following tests will be run as per the changes made to the code :
1. test (consul_acl_enabled, consul_acl_allow, nomad_acl_enabled)
2. test (consul_acl_enabled, consul_acl_allow, nomad_acl_disabled)
3. test (consul_acl_enabled, consul_acl_deny, nomad_acl_enabled)
4. test (consul_acl_enabled, consul_acl_deny, nomad_acl_disabled)
5. test (consul_acl_disabled, consul_acl_allow, nomad_acl_enabled)
6. test (consul_acl_disabled, consul_acl_allow, nomad_acl_disabled)
=> Added matrix test strategy for nomad acl enabled or disabled

.github/workflows/on_pr_master.yml, README.md, docs/SystemConfiguration.md
- Added a new file : docs/SystemConfiguration.md
- Modified README.md
=> Documentation sys config

CHANGELOG.md, template/example/nomad/countdash.hcl
=> Healthcheck example

template/.github/action/create-env.py, template/.github/linters/.markdown-lint.yml, template/.github/workflows/on_pr_push_master.yml, template/Makefile, template/README.md, template/ansible/README.md
=> Github actions for template

template/Makefile, template/README.md, template/dev/README.md, template/docker/README.md
@fredrikhgrelland not sure if this is a help or contributing to the chaos, let me know!
=> added docker-build + cleanup

.github/workflows/on_pr_master.yml, README.md, ansible/bootstrap.yml, ansible/test_enterprise.yml, docs/SystemConfiguration.md, template/.github/workflows/on_pr_push_master.yml
=> Hashicorp enterprise GitHub action changes

template/README.md
Updating documentation based on addition of enterprise switches.
=> template enterprise versions doc

CHANGELOG.md, template/Vagrantfile, template/dev/ansible/playbook.yml
=> Fix template bugs

CHANGELOG.md, packer/Vagrantfile
=> Template pre ansible niceness

CHANGELOG.md, template/README.md
=> Changed "Use this template" to button in template/README.md

CHANGELOG.md, template/README.md
=> "Where to start" doc update

.github/workflows/on_pr_master.yml, CHANGELOG.md
=> CI improvements

Makefile
=> Added link to the proxy section

CHANGELOG.md, ansible/bootstrap.yml, ansible/nomad_acl_bootstrap.yml, ansible/vault_consul_integration.yml, ansible/vault_nomad_integration.yml
I have tried to solve this issue by making use of custom facts in ansible. There surely would be a better way to fix this and so i am open to suggestions :)
closes #234
=> Make the bootstrap process idempotent

CHANGELOG.md, template/Makefile, template/README.md, template/README_template.md
=> README template

CHANGELOG.md, template/README.md
=> Change resources

test/Makefile
=> Corrected reference in test/Makefile

.github/action/create-env.py, .github/action/find-replace.py, CHANGELOG.md, ansible/install.yml, template/.github/action/create-env.py
Corrected the file path for .env file in install.yml.
=> Modidfied code so as .env file is sourced correctly

CHANGELOG.md, template/CHANGELOG.md, template/README.md
Closes #277 
Added `CHANGELOG.md` to template folder
Should we also add a section for how to use the CHANGELOG in the README?
=> Added changelog.md to template

.github/linters/.tflint.hcl, CHANGELOG.md, docs/CONTRIBUTING.md, template/.github/linters/.tflint.hcl, template/README.md, template/example/vagrant_box_example/main.tf, template/template_example/example/standalone/main.tf, template/template_example/example/standalone/variables.tf, template/template_example/outputs.tf
=> Linting for TF files + documentation

CHANGELOG.md, ansible/group_vars/all/variables.yml
=> Bump hashistack versions

CHANGELOG.md
=> Prepare for release 0.4.1

.github/workflows/on_pr_master.yml, CHANGELOG.md
=> Release 0.4.1

CHANGELOG.md, README.md, ansible/bootstrap.yml, ansible/install.yml, ansible/templates/.env_default.j2, ansible/terraform/vault_pki/main.tf
=> Vault PKI enabled

.gitmodules, CHANGELOG.md, Makefile, ansible/templates/update-motd.d/98-hashistack.j2, ansible/templates/update-motd.d/99-help-text.j2
=> Bug fixes for make update-submodule target and help text

CHANGELOG.md, ansible/group_vars/all/variables.yml, ansible/templates/vault.hcl.j2, docs/CONTRIBUTING.md, install/Makefile
=> Updated CONTRIBUTING.md, added plugin directory in vault hcl file

CHANGELOG.md, README.md
Closes #358 
Can someone please help me fill in the versions where the :shrug:-emoji is? I'm not able to use the box from my private mac 😅
=> Adding versions section to readme

CHANGELOG.md, README.md, ansible/templates/nomad.hcl.j2
=> Feature nomad vault integration

CHANGELOG.md, README.md
Offer https://github.com/fredrikhgrelland/vagrant-hashistack/issues/343#issuecomment-704882273
Option 2
=> Feature - custom port forwarding documentation

CHANGELOG.md, README.md
=> Added macos proxy section

CHANGELOG.md, README.md
Closes 1/3 tasks in #399 
- Updated section configuration
=> Updated section configuration

CHANGELOG.md, README.md
closes 1/3 of tasks in #399 
updated build section in README.md
=> updated build section in README.md

CHANGELOG.md, README.md
- Closes #396
CD/CI badge point to the last PR, not to the master branch
=> Fix CD/CI link

.github/workflows/on_pr_master.yml, CHANGELOG.md, README.md
Closes #396
Closes #416 
Github workflow (CI/CD) test for `push` changes on `master` branch.
Changelog was updated in this PR: https://github.com/fredrikhgrelland/vagrant-hashistack/pull/415
=> Updated workflow to test master branch on push

.github/workflows/on_pr_master.yml, CHANGELOG.md
Closes #419
Changelog enforcer also check on pull request
https://github.com/fredrikhgrelland/vagrant-hashistack/pull/418#issuecomment-712063386
=> Hotfix changelog enforcer

.github/workflows/on_pr_master.yml, CHANGELOG.md
closes #392 
Changed from using set-env to using env-files
=> Converted to use envfile in workflows

CHANGELOG.md, ansible/files/bootstrap/vault/post/810-tests.yml
Closes #347 
- Added test for Vault PKI
=> Added test for Vault PKI

CHANGELOG.md, install/mac/Makefile
Closes #363 
- Added message when brew is found
=> Added message when brew is found

Makefile
#430 
Nothing added, just separated a recipe into several targets.
=> refactored makefile

CHANGELOG.md, ansible/templates/conf/consul/010-consul.hcl
- Closes #393 
Remove recursor from consul configuration
=> Remove recursors

CHANGELOG.md, ansible/files/bootstrap/example.post_ansible.sh, ansible/files/bootstrap/example.pre_ansible.sh
Closes #438 
Removed shellscripts
=> Removed shellscripts

CHANGELOG.md
patch release
update changelog
=> Prepare patch release 0.7.1

.github/workflows/on_pr_master.yml, CHANGELOG.md
=> Release 0.8.0

.github/workflows/on_pr_master.yml, CHANGELOG.md
No issue
Reverting & fix workflow job
=> Reverting & fix workflow job

.github/workflows/on_pr_master.yml, CHANGELOG.md
=> Version 0.10

.github/workflows/on_pr_master.yml, CHANGELOG.md
=> Fix release process

.github/workflows/on_pr_master.yml, CHANGELOG.md
=> Lint only changed files on Pull Requests #494

.github/pull_request_template.md, .github/workflows/on_pr_master.yml, CHANGELOG.md
=> fix scheduled run #493

.github/workflows/on_pr_master.yml, CHANGELOG.md, ansible/files/bootstrap/consul/post/810-tests.yml, ansible/files/bootstrap/vault/post/810-tests.yml, ansible/roles/service_bootstrap/tasks/2-pre.yml, ansible/roles/service_bootstrap/tasks/3-start.yml, ansible/roles/service_bootstrap/tasks/4-post.yml
=> Fix ansible warnings
